# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion de la imagen')),
                ('imagen', models.ImageField(upload_to='productos', verbose_name='Imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
