# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180823_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_imagenes', to='productos.Producto'),
        ),
    ]
