# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180824_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 17, 22, 57, 548000, tzinfo=utc), verbose_name='date published'),
        ),
    ]
